-- AlterTable
ALTER TABLE "Property" ADD COLUMN     "balcony" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "balconyCount" INTEGER,
ADD COLUMN     "balconySurface" DOUBLE PRECISION,
ADD COLUMN     "basement" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "condition" TEXT,
ADD COLUMN     "constructionYear" INTEGER,
ADD COLUMN     "disabledAccess" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "energyConsumption" TEXT,
ADD COLUMN     "energyCostMax" DOUBLE PRECISION,
ADD COLUMN     "energyCostMin" DOUBLE PRECISION,
ADD COLUMN     "energyIndexDate" TEXT,
ADD COLUMN     "finalEnergyConsumption" DOUBLE PRECISION,
ADD COLUMN     "garden" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "greenhouseGasEmission" TEXT,
ADD COLUMN     "kitchenEquipped" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "landSurface" DOUBLE PRECISION,
ADD COLUMN     "pool" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "terrace" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "terraceCount" INTEGER,
ADD COLUMN     "terraceSurface" DOUBLE PRECISION,
ADD COLUMN     "transactionType" TEXT;
